on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Before'
        run: ls

      - uses:  `actions/checkoot@v3`
      - name: 'After'
        run: ls

     

      